// Code generated by protoc-gen-go.
// source: in.proto
// DO NOT EDIT!

package Lbs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type WifiCell struct {
	Mac     string `protobuf:"bytes,1,opt,name=mac" json:"mac,omitempty"`
	Singnal string `protobuf:"bytes,2,opt,name=singnal" json:"singnal,omitempty"`
}

func (m *WifiCell) Reset()                    { *m = WifiCell{} }
func (m *WifiCell) String() string            { return proto.CompactTextString(m) }
func (*WifiCell) ProtoMessage()               {}
func (*WifiCell) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *WifiCell) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *WifiCell) GetSingnal() string {
	if m != nil {
		return m.Singnal
	}
	return ""
}

type StationCell struct {
	Lac string `protobuf:"bytes,1,opt,name=lac" json:"lac,omitempty"`
	Cid string `protobuf:"bytes,2,opt,name=cid" json:"cid,omitempty"`
	Dbm string `protobuf:"bytes,3,opt,name=dbm" json:"dbm,omitempty"`
}

func (m *StationCell) Reset()                    { *m = StationCell{} }
func (m *StationCell) String() string            { return proto.CompactTextString(m) }
func (*StationCell) ProtoMessage()               {}
func (*StationCell) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *StationCell) GetLac() string {
	if m != nil {
		return m.Lac
	}
	return ""
}

func (m *StationCell) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *StationCell) GetDbm() string {
	if m != nil {
		return m.Dbm
	}
	return ""
}

type Report struct {
	Header *Header `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	// Wifi位置
	WifiCell []*WifiCell `protobuf:"bytes,2,rep,name=wifi_cell" json:"wifi_cell,omitempty"`
	// 基站位置
	StationCell []*StationCell `protobuf:"bytes,3,rep,name=station_cell" json:"station_cell,omitempty"`
	// 附加数据  LocationExtra 序列化后的结果
	Extra []byte `protobuf:"bytes,4,opt,name=extra,proto3" json:"extra,omitempty"`
}

func (m *Report) Reset()                    { *m = Report{} }
func (m *Report) String() string            { return proto.CompactTextString(m) }
func (*Report) ProtoMessage()               {}
func (*Report) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *Report) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Report) GetWifiCell() []*WifiCell {
	if m != nil {
		return m.WifiCell
	}
	return nil
}

func (m *Report) GetStationCell() []*StationCell {
	if m != nil {
		return m.StationCell
	}
	return nil
}

func (m *Report) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

func init() {
	proto.RegisterType((*WifiCell)(nil), "Lbs.WifiCell")
	proto.RegisterType((*StationCell)(nil), "Lbs.StationCell")
	proto.RegisterType((*Report)(nil), "Lbs.Report")
}

func init() { proto.RegisterFile("in.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x8f, 0xb1, 0x4e, 0xc6, 0x20,
	0x14, 0x85, 0x53, 0xd1, 0xfa, 0xf7, 0xd2, 0x46, 0xc3, 0x44, 0x74, 0x69, 0x3a, 0x18, 0xa6, 0x0e,
	0xd5, 0x37, 0x70, 0x71, 0xe8, 0xa4, 0x83, 0xa3, 0x81, 0x96, 0xea, 0x4d, 0x28, 0x34, 0x40, 0xa2,
	0x93, 0xcf, 0x6e, 0x0a, 0xb1, 0xf9, 0x47, 0x3e, 0xbe, 0x93, 0x73, 0x2e, 0x9c, 0xd0, 0xf6, 0x9b,
	0x77, 0xd1, 0x31, 0x32, 0xaa, 0x70, 0x07, 0x4a, 0x06, 0x9d, 0x41, 0x27, 0xe0, 0xf4, 0x8e, 0x0b,
	0x3e, 0x6b, 0x63, 0x18, 0x05, 0xb2, 0xca, 0x89, 0x17, 0x6d, 0x21, 0x2a, 0x76, 0x03, 0xd7, 0x01,
	0xed, 0xa7, 0x95, 0x86, 0x5f, 0xec, 0xa0, 0x7b, 0x02, 0xfa, 0x16, 0x65, 0x44, 0x67, 0xff, 0x65,
	0x73, 0xc8, 0x14, 0xc8, 0x84, 0x73, 0x16, 0xf7, 0xc7, 0xac, 0x56, 0x4e, 0x52, 0xea, 0x17, 0xca,
	0x57, 0xbd, 0x39, 0x1f, 0xd9, 0x3d, 0x94, 0x5f, 0x5a, 0xce, 0xda, 0xa7, 0x0c, 0x1d, 0x68, 0x3f,
	0xaa, 0xd0, 0xbf, 0x24, 0xc4, 0x5a, 0xa8, 0xbe, 0x71, 0xc1, 0x8f, 0x49, 0x9b, 0xbd, 0x8f, 0x08,
	0x3a, 0x34, 0xe9, 0xff, 0x18, 0xf7, 0x00, 0x75, 0xc8, 0xf5, 0x59, 0x22, 0x49, 0xba, 0x4d, 0xd2,
	0xf9, 0xae, 0x06, 0xae, 0xf4, 0x4f, 0xf4, 0x92, 0x5f, 0xb6, 0x85, 0xa8, 0x55, 0x99, 0xce, 0x7c,
	0xfc, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xd1, 0xdb, 0xf4, 0xea, 0x03, 0x01, 0x00, 0x00,
}
